[versions]
alchemist = "24.1.16"
upickle = "2.0.0"
smile = "2.6.0"
oslib = "0.8.1"
ui = "5.0.0"
breeze = "2.1.0"
scalapy = "0.5.2+8-f74f8dfe"
scrimage = "4.0.32"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-incarnation-protelis = { module = "it.unibo.alchemist:alchemist-incarnation-protelis", version.ref = "alchemist" }
alchemist-swingui = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-ui-tooling = { module = "it.unibo.alchemist:alchemist-ui-tooling", version.ref = "alchemist" }
alchemist-incarnation-scafi = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist"}
tooling-gui = { module = "org.danilopianini:javalib", version.ref = "ui" }
upickle = { module = "com.lihaoyi:upickle_2.13", version.ref = "upickle" }
smile = { module = "com.github.haifengl:smile-scala_2.13", version.ref = "smile" }
oslib = { module = "com.lihaoyi:os-lib_2.13", version.ref = "oslib" }
breezelib = { module = "org.scalanlp:breeze_2.13", version.ref = "breeze" }
scalapy = { module = "me.shadaj:scalapy-core_2.13", version.ref = "scalapy" }
scrimage = { module = "com.sksamuel.scrimage:scrimage-scala_2.13", version.ref = "scrimage" }

[bundles]
alchemist = ["alchemist", "alchemist-incarnation-scafi", "alchemist-swingui", "alchemist-incarnation-protelis", "alchemist-ui-tooling", "tooling-gui"]

[plugins]
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.4.13"
taskTree = "com.dorongold.task-tree:2.1.0"
